# Change these first
owner: alluvialfinance # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Alluvial API
    url: https://api.alluvial.finance
  - name: Alluvial API Staging
    url: https://api.staging.alluvial.finance
  - name: Liquid Collective Website
    url: https://liquidcollective.io
  - name: Alluvial Website
    url: https://alluvial.finance

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.alluvial.finance
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/AlluvialFinance/upptime/master/logo.svg
  name: Alluvial
  introTitle: "**Alluvial**, building the enterprise-grade liquid staking standard"

  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/alluvialfinance/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/alluvialfinance/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
